"""empty message

Revision ID: 209731eedc6e
Revises: bc94f3b3f5ec
Create Date: 2018-02-28 20:30:10.073907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209731eedc6e'
down_revision = 'bc94f3b3f5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'deleted')
    # ### end Alembic commands ###
