"""rename make up time to create_at

Revision ID: 37005aefe1a6
Revises: 302cef366d31
Create Date: 2018-03-09 09:23:13.542854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37005aefe1a6'
down_revision = '302cef366d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.drop_column('note', 'make_up_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('make_up_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('note', 'create_at')
    # ### end Alembic commands ###
