"""empty message

Revision ID: bc94f3b3f5ec
Revises: c37d83c695a5
Create Date: 2018-02-20 11:30:42.232203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc94f3b3f5ec'
down_revision = 'c37d83c695a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite_color', sa.CHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorite_color')
    # ### end Alembic commands ###
